### ISSUE TITLE
Fix broken image links

### ISSUE THREAD

**Issue by tobiashein** [ploetz-zeller/symbio-documentation#11]
# Problem
Some of the images are not displayed correctly because references are case-sensitive and the link and file do not match.

## Example
Link: `![Navigate to storages](media/NavigateToStorages.png "Navigate to storages")`
File: media/NavigateToStorages.PNG

# Solution
Make all file extensions lowercase and adjust the links accordingly.

**Comment by PZ-CFDuToit** [comment]
Fixed across all documents. Changed the references to capitals
